### ISSUE TITLE
[Question] I need help please!!!Report someone using personal space to set up a pornographic website

### ISSUE THREAD

**Issue by kioxxa1** [CMakePP/.github#11]
**Before opening this issue I:**

- [ ] Checked the documentation for answers
- [ ] Looked for similar issues
- [ ] Did a quick internet search
Report someone using personal space to set up a pornographic website
Report someone using personal space to set up a pornographic website
Report someone using personal space to set up a pornographic website

![image](https://user-images.githubusercontent.com/124401592/216709291-1982bfd5-5551-45de-83bc-b8c1ad7c120c.png)

https://xiaoxing66.github.io/Sdian/165-sd666.cos.html?202302033655=%E8%BD%AC%E5%8F%91%E6%B0%B8%E4%B9%85%E4%BF%9D%E5%AD%98=%E7%82%B9+%E6%88%91+%E6%9C%89+%E6%83%8A+%E5%96%9C=https%3A%2F%2Fjq.qq.com%2F%3F%5Fwv%3D1027%26k%3DePEvb7vd=FF8000=1=1=1

Report someone using personal space to set up a pornographic website
Report someone using personal space to set up a pornographic website
Report someone using personal space to set up a pornographic website

**Comment by ryanmrichard** [comment]
Does this actually apply to the CMakePP repo? It looks like it applies to your personal website.

**Comment by zachcran** [comment]
This issue is stale and appears to be unrelated to CMakePP, so I am closing it for now. Please let us know if you run into any issues in the future relating to CMakePP and we will be happy to help!
